import { join } from "node:path";

import { MAP_FIELDS } from "@/data/map";
import { gameReducer } from "@/lib/game-state";
import { drainAiTurn } from "@/lib/test-utils";
import type { CountryId, GameState } from "@/types";

/**
 * Where the committed baseline report lives (regenerated byte-identically).
 * Anchored to this module so regeneration works from any cwd (review F4).
 * The change archived to context/archive/ on 2026-09-13; the report moved with it.
 */
export const BASELINE_REPORT_PATH = join(
  import.meta.dirname,
  "../../context/archive/2026-09-13-testing-balance-simulation/baseline-report.md",
);

/**
 * Balance simulation harness (change: testing-balance-simulation, test-plan
 * Phase 2, risk #1): drives full AI-vs-AI campaigns through the real reducer
 * with alternating role assignment, and collects the metrics a balance
 * baseline needs. Pure and seeded — the same input always yields the same
 * record, so measured distributions are exactly reproducible.
 *
 * Test-only measurement tool: never import from src/pages or src/components —
 * it pulls vitest into the module graph via @/lib/test-utils (review F3).
 *
 * One "turn" here is one endTurn cycle (one side's action phase); a full
 * round of both sides is 2 turns. The role swap happens between turns, after
 * the plan drains — never mid-plan (research audited every role read:
 * economy, victory anchoring, production and report slots are role-agnostic).
 */

/** A single campaign's inputs; `playerCountryId` is the side acting first. */
export interface CampaignInput {
  seed: number;
  playerCountryId: CountryId;
  /** Turn-cycle cap: the stalemate guard (no draw rule exists in the engine). */
  maxTurns: number;
}

/** A single campaign's measured outcome. */
export interface CampaignRecord {
  /** The side that acted first (the other role assignment is the mirror). */
  playerCountryId: CountryId;
  /** The campaign's winner, or null when the turn cap hit first. */
  winner: CountryId | null;
  /** Number of turn cycles executed (= length of each income array). */
  endTurn: number;
  /** Battles fought by either side across the whole campaign. */
  battles: number;
  /** Battles where the strictly weaker pre-roll side won (US-01 upsets). */
  upsets: number;
  /** Per-turn total city income (money+steel+recruits) per country, from live ownership. */
  incomeByTurn: Record<CountryId, number[]>;
}

/** Total per-turn city income of `country` under current ownership. */
function incomeAt(state: GameState, country: CountryId): number {
  let total = 0;
  for (const field of MAP_FIELDS) {
    if (field.city !== null && state.fieldOwners[field.id] === country) {
      total += field.city.income.money + field.city.income.steel + field.city.income.recruits;
    }
  }
  return total;
}

/** Counts the turn's battles and strength upsets from the drained AI turn log. */
function battlesInTurn(state: GameState): { battles: number; upsets: number } {
  let battles = 0;
  let upsets = 0;
  for (const entry of state.aiTurnLog) {
    if (entry.kind !== "battle") continue;
    battles += 1;
    const { attackStrength, defenseStrength, attackerWins } = entry.report;
    const weakerWon =
      (attackerWins && attackStrength < defenseStrength) || (!attackerWins && defenseStrength < attackStrength);
    if (weakerWon) upsets += 1;
  }
  return { battles, upsets };
}

/**
 * Runs one AI-vs-AI campaign: endTurn → drain → swap roles → repeat, until a
 * winner emerges or the turn cap is reached. Both sides play through the
 * identical AI code (`planAiTurn`/`aiStep`/`planAiProduction`); the idle
 * "player" role exists only to satisfy the reducer's turn structure.
 */
export function runCampaign(input: CampaignInput): CampaignRecord {
  const aiCountryId: CountryId = input.playerCountryId === "germany" ? "soviet" : "germany";
  let state = gameReducer(null, {
    type: "startGame",
    playerCountryId: input.playerCountryId,
    aiCountryId,
    seed: input.seed,
  });
  if (state === null) throw new Error("startGame returned null");

  let endTurn = 0;
  let battles = 0;
  let upsets = 0;
  const incomeByTurn: Record<CountryId, number[]> = { germany: [], soviet: [] };

  while (state.winner === null && endTurn < input.maxTurns) {
    // Income from live ownership, before this turn's captures move it.
    incomeByTurn.germany.push(incomeAt(state, "germany"));
    incomeByTurn.soviet.push(incomeAt(state, "soviet"));

    const planned = gameReducer(state, { type: "endTurn" });
    if (planned === null) throw new Error(`endTurn returned null on turn ${endTurn + 1}`);
    const drained = drainAiTurn(planned, `campaign seed ${input.seed}, turn ${endTurn + 1}`);

    const turnBattles = battlesInTurn(drained);
    battles += turnBattles.battles;
    upsets += turnBattles.upsets;
    endTurn += 1;

    if (drained.winner !== null) {
      state = drained; // mid-replay victory: frozen, no rollover — clean exit
      break;
    }

    // Role swap between turns: the other side becomes the AI for its phase.
    state = { ...drained, playerCountryId: drained.aiCountryId, aiCountryId: drained.playerCountryId };
  }

  return { playerCountryId: input.playerCountryId, winner: state.winner, endTurn, battles, upsets, incomeByTurn };
}

// --- Grid, summary, and report rendering ------------------------------------

/** The pinned baseline grid: seeds 0–49 × both role assignments, 100 campaigns. */
export const BASELINE_GRID = {
  seeds: Array.from({ length: 50 }, (_, seed) => seed),
  roles: ["germany", "soviet"] as const,
  maxTurns: 60,
};

/** Runs the mirrored grid deterministically (grid order: seed-major, role-minor). */
export function runGrid(grid: typeof BASELINE_GRID = BASELINE_GRID): CampaignRecord[] {
  const records: CampaignRecord[] = [];
  for (const seed of grid.seeds) {
    for (const playerCountryId of grid.roles) {
      records.push(runCampaign({ seed, playerCountryId, maxTurns: grid.maxTurns }));
    }
  }
  return records;
}

/** Aggregate of a record set — everything the descriptive baseline reports. */
export interface BalanceSummary {
  campaigns: number;
  wins: Record<CountryId, number>;
  noWinner: number;
  decided: number;
  /** Decided-campaign win rate per country (0–1); NaN-free: 0 when nothing decided. */
  winRate: Record<CountryId, number>;
  endTurnMin: number;
  endTurnMedian: number;
  endTurnMax: number;
  battles: number;
  upsets: number;
  /** Upsets as a share of battles (0 when battleless). */
  upsetRate: number;
  /** Per-turn ratio of summed income (germany/soviet); entry t covers campaigns still running. */
  incomeRatioByTurn: number[];
}

export function summarize(records: CampaignRecord[]): BalanceSummary {
  const wins: Record<CountryId, number> = { germany: 0, soviet: 0 };
  for (const record of records) {
    if (record.winner !== null) wins[record.winner] += 1;
  }
  const noWinner = records.length - wins.germany - wins.soviet;
  const decided = wins.germany + wins.soviet;
  const turns = [...records].sort((a, b) => a.endTurn - b.endTurn).map((record) => record.endTurn);
  const middle = Math.floor(turns.length / 2);
  const battles = records.reduce((sum, record) => sum + record.battles, 0);
  const upsets = records.reduce((sum, record) => sum + record.upsets, 0);
  const maxTurnsRun = turns.reduce((max, turn) => Math.max(max, turn), 0);
  const incomeRatioByTurn: number[] = [];
  for (let turn = 0; turn < maxTurnsRun; turn += 1) {
    let germany = 0;
    let soviet = 0;
    for (const record of records) {
      germany += record.incomeByTurn.germany[turn] ?? 0;
      soviet += record.incomeByTurn.soviet[turn] ?? 0;
    }
    incomeRatioByTurn.push(soviet > 0 ? germany / soviet : Number.POSITIVE_INFINITY);
  }
  return {
    campaigns: records.length,
    wins,
    noWinner,
    decided,
    winRate: { germany: decided > 0 ? wins.germany / decided : 0, soviet: decided > 0 ? wins.soviet / decided : 0 },
    endTurnMin: turns[0] ?? 0,
    endTurnMedian:
      turns.length % 2 === 1 ? (turns[middle] ?? 0) : ((turns[middle - 1] ?? 0) + (turns[middle] ?? 0)) / 2,
    endTurnMax: turns[turns.length - 1] ?? 0,
    battles,
    upsets,
    upsetRate: battles > 0 ? upsets / battles : 0,
    incomeRatioByTurn,
  };
}

function pct(value: number): string {
  return `${(value * 100).toFixed(1)}%`;
}

function summaryTable(label: string, summary: BalanceSummary): string[] {
  return [
    `### ${label}`,
    "",
    "| Metric | Value |",
    "| --- | --- |",
    `| Campaigns | ${summary.campaigns} |`,
    `| Germany wins | ${summary.wins.germany} (${pct(summary.winRate.germany)} of decided) |`,
    `| Soviet wins | ${summary.wins.soviet} (${pct(summary.winRate.soviet)} of decided) |`,
    `| No winner by cap | ${summary.noWinner} |`,
    `| Campaign length (turn cycles): min / median / max | ${summary.endTurnMin} / ${summary.endTurnMedian} / ${summary.endTurnMax} |`,
    `| Battles | ${summary.battles} |`,
    `| Upsets (weaker pre-roll side won) | ${summary.upsets} (${pct(summary.upsetRate)} of battles) |`,
    "",
  ];
}

/** Renders the committed baseline report. Deterministic: no timestamps, no wall clock. */
export function renderBaselineReport(records: CampaignRecord[]): string {
  const germanyFirst = records.filter((record) => record.playerCountryId === "germany");
  const sovietFirst = records.filter((record) => record.playerCountryId === "soviet");
  const lines: string[] = [
    "# Balance Baseline — AI-vs-AI Simulation (descriptive)",
    "",
    "Measured by the balance simulation harness (test-plan Phase 2, risk #1).",
    "Descriptive only: **no numeric fairness bands are pinned here** — this report is the",
    "input for a future user-owned decision to pin bands (the descriptive-first call).",
    "",
    `- Grid: seeds ${BASELINE_GRID.seeds[0]}–${BASELINE_GRID.seeds[BASELINE_GRID.seeds.length - 1]} × both role assignments = ${records.length} campaigns`,
    `- Turn cap: ${BASELINE_GRID.maxTurns} turn cycles (1 cycle = one side's action phase; a full round of both sides = 2 cycles)`,
    "- Regenerate byte-identically: `BALANCE_WRITE=1 npx vitest run src/lib/balance-simulation.test.ts`",
    "",
    ...summaryTable("Combined (both role assignments)", summarize(records)),
    ...summaryTable("Germany acts first", summarize(germanyFirst)),
    ...summaryTable("Soviet acts first", summarize(sovietFirst)),
    "### Income divergence (combined)",
    "",
    "Ratio of summed per-turn city income (Germany / Soviet); 1.0 = economic parity.",
    "",
    "| Turn cycle | Income ratio |",
    "| --- | --- |",
  ];
  const combined = summarize(records);
  for (let turn = 0; turn < combined.incomeRatioByTurn.length; turn += 1) {
    const ratio = combined.incomeRatioByTurn[turn];
    lines.push(`| ${turn + 1} | ${Number.isFinite(ratio) ? ratio.toFixed(2) : "∞ (soviet income 0)"} |`);
  }
  lines.push(
    "",
    "### Measurement caveats (measured as-is, see research)",
    "",
    '- German "Blitzkrieg" national bonus is advertised in the UI but not implemented; the Soviet recruit discount is live.',
    "- `bonusVsTank` is never read by the engine; antiTank is dominated by infantry.",
    "- Germany's start is front-loaded (Warsaw is a German-initial city 1 move from Soviet territory) with +6% money / +17% steel.",
    "- Consecutive mulberry32 draws correlate (~0.07 near even strengths) — any future 50/50 oracle needs a tolerance band.",
    "",
  );
  return lines.join("\n");
}
